"""add queue ready index

Revision ID: 4271f960e24b
Revises: d20d98bf3286
Create Date: 2026-09-10 19:38:39.095947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4271f960e24b'
down_revision: Union[str, None] = 'd20d98bf3286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.create_index('ix_review_runs_queue_ready', ['status', 'next_attempt_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_review_runs_queue_ready')

    # ### end Alembic commands ###
