"""dashboard sessions

Revision ID: bb37708c03df
Revises: e31dba0b2a58
Create Date: 2026-09-10 18:45:50.340394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb37708c03df'
down_revision: Union[str, None] = 'e31dba0b2a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('csrf_token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_sessions_github_login'), ['github_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_sessions_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_dashboard_sessions_github_login'))
        batch_op.drop_index(batch_op.f('ix_dashboard_sessions_expires_at'))

    op.drop_table('dashboard_sessions')
    # ### end Alembic commands ###
