"""limit model calls

Revision ID: d20d98bf3286
Revises: bb37708c03df
Create Date: 2026-09-10 19:25:11.456678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20d98bf3286'
down_revision: Union[str, None] = 'bb37708c03df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_configs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('max_model_calls', sa.Integer(), server_default='20', nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_configs', schema=None) as batch_op:
        batch_op.drop_column('max_model_calls')

    # ### end Alembic commands ###
