"""mvp schema

Revision ID: e31dba0b2a58
Revises: da63a9674257
Create Date: 2026-09-10 17:22:46.132931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31dba0b2a58'
down_revision: Union[str, None] = 'da63a9674257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_installations_github_installation_id'), ['github_installation_id'], unique=True)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('pull_number', sa.Integer(), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_github_delivery_id'), ['github_delivery_id'], unique=True)

    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_repository_id', sa.BigInteger(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['github_installation_id'], ['github_installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_github_installation_id'), ['github_installation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_github_repository_id'), ['github_repository_id'], unique=True)

    op.create_table('review_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('discord_webhook_encrypted', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('minimum_severity', sa.String(length=20), nullable=False),
    sa.Column('ignored_paths', sa.JSON(), nullable=False),
    sa.Column('trigger_events', sa.JSON(), nullable=False),
    sa.Column('ignore_drafts', sa.Boolean(), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('max_files', sa.Integer(), nullable=False),
    sa.Column('max_diff_lines', sa.Integer(), nullable=False),
    sa.Column('max_findings', sa.Integer(), nullable=False),
    sa.Column('max_input_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_table('review_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('pull_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk', sa.String(length=20), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('skipped_files', sa.Integer(), nullable=False),
    sa.Column('skipped_lines', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'pull_number', 'head_sha', name='uq_review_run_idempotency')
    )
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_runs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_runs_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_runs_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_runs_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_run_id', 'fingerprint', name='uq_finding_fingerprint')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_review_run_id'), ['review_run_id'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('message_ids', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_review_run_id'), ['review_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_review_run_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_review_run_id'))
        batch_op.drop_index(batch_op.f('ix_findings_fingerprint'))

    op.drop_table('findings')
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_runs_status'))
        batch_op.drop_index(batch_op.f('ix_review_runs_repository_id'))
        batch_op.drop_index(batch_op.f('ix_review_runs_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_review_runs_lease_expires_at'))

    op.drop_table('review_runs')
    op.drop_table('review_configs')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_github_repository_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_github_installation_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_github_delivery_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_installations_github_installation_id'))

    op.drop_table('github_installations')
    # ### end Alembic commands ###
